### ISSUE TITLE
Is there a way to store the map?

### ISSUE THREAD

**Issue by ZikeYan** [mrfmap/mrfmap_ros#2]
Hello. I didn't find the interface to save the map. Meanwhile, the visualization is different from that in your RSS paper. I wonder if there is a way to output the map of yours and Octomap into .bt format for further evaluation and visualization?

**Comment by icoderaven** [comment]
Hi Zike! The only interface to access the data for all the active bricks from an MRFMap object is to get tuples of occupied voxels via 
https://github.com/mrfmap/mrfmap/blob/9ccbca8454ebc3cec825d00d7acaf4830720068d/include/mrfmap/GVDBMRFMap.h#L59

Here's an instance of the python script accessing the voxel data and saving it as a binary numpy file to disk
https://github.com/mrfmap/mrfmap_ros/blob/8c1e108860ff297f39591d97f8f8ce2937b29a51/nodes/dataset_evaluation/rss_dataset_eval.py#L115
(Which is internally calling this method:
https://github.com/mrfmap/mrfmap_ros/blob/8c1e108860ff297f39591d97f8f8ce2937b29a51/src/mrfmap_ros/MRFMapGenerator.py#L38
)

To save it in a custom file format you'll have to write a wrapper to do so with the voxel location and occupancy data. Hope that's helpful!

Regarding visualisation, could you clarify which visualisation are you talking about?

**Comment by ZikeYan** [comment]
> Hi Zike! The only interface to access the data for all the active bricks from an MRFMap object is to get tuples of occupied voxels via
> https://github.com/mrfmap/mrfmap/blob/9ccbca8454ebc3cec825d00d7acaf4830720068d/include/mrfmap/GVDBMRFMap.h#L59
> 
> Here's an instance of the python script accessing the voxel data and saving it as a binary numpy file to disk
> https://github.com/mrfmap/mrfmap_ros/blob/8c1e108860ff297f39591d97f8f8ce2937b29a51/nodes/dataset_evaluation/rss_dataset_eval.py#L115
> 
> 
> (Which is internally calling this method:
> https://github.com/mrfmap/mrfmap_ros/blob/8c1e108860ff297f39591d97f8f8ce2937b29a51/src/mrfmap_ros/MRFMapGenerator.py#L38
> 
> 
> )
> To save it in a custom file format you'll have to write a wrapper to do so with the voxel location and occupancy data. Hope that's helpful!
> 
> Regarding visualisation, could you clarify which visualisation are you talking about?

The Pangolin visualization is different from Fig. 8 of your paper(attached as follows).
Another issue is about the intrinsic matrix. Can mrfmap accept negative focal length (Original ICL-NUIM)? I generate a new bag file from original ICL-NUIM livingroom kt-1, but the projected point cloud is not correct. Bag file from Burghers dataset is working fine.
![Screenshot from 2020-11-11 12-21-21](https://user-images.githubusercontent.com/28919685/98765242-a4585700-2418-11eb-8b38-06a21498f7b9.png)

**Comment by icoderaven** [comment]
Hi! Fig 8 was the Mayavi generated rendering of the inferred volume of the ICL NUIM bag - did you forget to upload a screenshot of that? Irrespective, if you can tell me how it is different it would be useful - there might be some config file parameters that I didn't change.

Well, I've designed it for 'normal' camera intrinsics. The negative focal length is a really annoying feature of the ICL NUIM dataset because of how they generated it (using POVRay) and I don't think a simple swap of one of the focal lengths will work for MRFMaps because the camera intrinsics are used for a lot of internal operations that would probably fail. I suggest reprojecting the dataset and generating a 'fixed' bag file for using the other datasets.

Another thing to note that I vaguely recall is that you might have to rotate the camera odometry to the ROS Z up coordinate frame. I think there's a special pre-rotation flag I have included for the ICL datasets to take that into account
e.g.
https://github.com/mrfmap/mrfmap_ros/blob/8c1e108860ff297f39591d97f8f8ce2937b29a51/config/ICL.yaml#L6
https://github.com/mrfmap/mrfmap_ros/blob/8c1e108860ff297f39591d97f8f8ce2937b29a51/config/ICL.yaml#L10
which is incorporated at
https://github.com/mrfmap/mrfmap_ros/blob/d4f1bfab2b2ce19586ef14bcf5a5727f8e655027/src/GVDBBatchMapCreator.cpp#L87

A sanity check is to make sure that the camera frustum isn't backprojecting the pointcloud beyond the volume boundaries in the Visualiser

**Comment by ZikeYan** [comment]
> Hi! Fig 8 was the Mayavi generated rendering of the inferred volume of the ICL NUIM bag - did you forget to upload a screenshot of that? Irrespective, if you can tell me how it is different it would be useful - there might be some config file parameters that I didn't change.
> 
> Well, I've designed it for 'normal' camera intrinsics. The negative focal length is a really annoying feature of the ICL NUIM dataset because of how they generated it (using POVRay) and I don't think a simple swap of one of the focal lengths will work for MRFMaps because the camera intrinsics are used for a lot of internal operations that would probably fail. I suggest reprojecting the dataset and generating a 'fixed' bag file for using the other datasets.
> 
> Another thing to note that I vaguely recall is that you might have to rotate the camera odometry to the ROS Z up coordinate frame. I think there's a special pre-rotation flag I have included for the ICL datasets to take that into account
> e.g.
> https://github.com/mrfmap/mrfmap_ros/blob/8c1e108860ff297f39591d97f8f8ce2937b29a51/config/ICL.yaml#L6
> 
> 
> https://github.com/mrfmap/mrfmap_ros/blob/8c1e108860ff297f39591d97f8f8ce2937b29a51/config/ICL.yaml#L10
> 
> 
> which is incorporated at
> https://github.com/mrfmap/mrfmap_ros/blob/d4f1bfab2b2ce19586ef14bcf5a5727f8e655027/src/GVDBBatchMapCreator.cpp#L87
> 
> A sanity check is to make sure that the camera frustum isn't backprojecting the pointcloud beyond the volume boundaries in the Visualiser

Hi, I managed to run it on ICL dataset by adjusting the projection and the corresponding volume boundary. Really appreciate your kindness for such thourough suggestions. It is a little bit late for me to find this repo and I am in a hurry. Nice work by the way!
